services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT
      - CIMAS_ACCOUNT_NAME
      - CIMAS_ACCOUNT_PASSWORD
      - CIMAS_CLAIMS_SWITCH_ENDPOINT
      - DATABASE_URL
      - CLIENT_URL
      - JWT_SECRET_KEY
      - JWT_ISSUER
      - JWT_AUDIENCE
      - VITE_SERVER_URL
    networks:
      - jude-network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: jude-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jude-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  jude-network:
    driver: bridge

volumes:
  postgres-data:
