name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set tag
        id: tag
        run: |
          echo "tag=$(git rev-parse "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ghcr.io/teamjude/jude:${{ steps.tag.outputs.tag }} --label service="peasy" -t ghcr.io/teamjude/jude:latest .

      - name: Push image
        run: |
          docker push ghcr.io/teamjude/jude:${{ steps.tag.outputs.tag }}

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: |
            docker-compose.prod.yml
            Caddyfile
          target: ~/jude

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/jude
      
            export CIMAS_ACCOUNT_NAME="${{ secrets.CIMAS_ACCOUNT_NAME }}"
            export CIMAS_ACCOUNT_PASSWORD="${{ secrets.CIMAS_ACCOUNT_PASSWORD }}"
            export CIMAS_CLAIMS_SWITCH_ENDPOINT="${{ secrets.CIMAS_CLAIMS_SWITCH_ENDPOINT }}"
            export DATABASE_URL="Host=${{secrets.POSTGRES_HOST}};Port=${{secrets.POSTGRES_PORT}};Database=${{secrets.POSTGRES_DB}};Username=${{secrets.POSTGRES_USER}};Password=${{secrets.POSTGRES_PASSWORD}};"
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"

            export CLIENT_URL="https://102.37.149.93"
            export JWT_ISSUER="https://102.37.149.93"
            export JWT_AUDIENCE="https://102.37.149.93"
            export VITE_SERVER_URL="https://102.37.149.93"

            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"

            export GITHUB_ACTOR="${{ github.actor }}"
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
                      
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose  -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d