name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set tag
        id: tag
        run: |
          echo "tag=$(git rev-parse "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ghcr.io/teamjude/jude:${{ steps.tag.outputs.tag }} -t ghcr.io/teamjude/jude:latest .

      - name: Push image
        run: |
          docker push ghcr.io/teamjude/jude:${{ steps.tag.outputs.tag }} 
          docker push ghcr.io/teamjude/jude:latest

      - name: Create Caddyfile from template
        run: |
          sed 's/\$\$APP_DOMAIN\$\$/${{ vars.APP_DOMAIN }}/g' Caddyfile.template > Caddyfile

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.prod.yml, Caddyfile"
          target: ~/jude

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/jude
      
            export CIMAS_ACCOUNT_NAME="${{ secrets.CIMAS_ACCOUNT_NAME }}"
            export CIMAS_ACCOUNT_PASSWORD="${{ secrets.CIMAS_ACCOUNT_PASSWORD }}"
            export CIMAS_CLAIMS_SWITCH_ENDPOINT="${{ secrets.CIMAS_CLAIMS_SWITCH_ENDPOINT }}"

            export CIMAS_PRACTICE_NUMBER="995630"

            export DATABASE_URL="Host=${{secrets.POSTGRES_HOST}};Port=${{secrets.POSTGRES_PORT}};Database=${{secrets.POSTGRES_DB}};Username=${{secrets.POSTGRES_USER}};Password=${{secrets.POSTGRES_PASSWORD}}"
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"

            export CLIENT_URL="https://102.37.149.93"
            export JWT_ISSUER="https://102.37.149.93"
            export JWT_AUDIENCE="https://102.37.149.93"
            export VITE_SERVER_URL="https://102.37.149.93"

            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"

            export AZURE_AI_APIKEY="${{ secrets.AZURE_AI_APIKEY }}"
            export AZURE_AI_ENDPOINT="${{ secrets.AZURE_AI_ENDPOINT }}"

            export GITHUB_ACTOR="${{ github.actor }}"
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"

            export CIMAS_PRICING_API_ENDPOINT="${{ secrets.CIMAS_PRICING_API_ENDPOINT }}"
            export CIMAS_PRICING_API_USERNAME="${{ secrets.CIMAS_PRICING_API_USERNAME }}"
            export CIMAS_PRICING_API_PASSWORD="${{ secrets.CIMAS_PRICING_API_PASSWORD }}"

            export VECTOR_DB_URL="${{ secrets.VECTOR_DB_URL }}"

            export CUSTOM_AZURE_AI_APIKEY="${{ secrets.CUSTOM_AZURE_AI_APIKEY }}"
            export CUSTOM_AZURE_AI_ENDPOINT="${{ secrets.CUSTOM_AZURE_AI_ENDPOINT }}"

            export AZURE_AI_SEARCH_APIKEY="${{ secrets.AZURE_AI_SEARCH_APIKEY }}"
            export AZURE_AI_SEARCH_ENDPOINT="${{ secrets.AZURE_AI_SEARCH_ENDPOINT }}"

            export AZURE_BLOB_ACCOUNT="${{ secrets.AZURE_BLOB_ACCOUNT }}"
            export AZURE_BLOB_ACESS_KEY="${{ secrets.AZURE_BLOB_ACESS_KEY }}"
            export AZURE_BLOB_CONTAINER="${{ secrets.AZURE_BLOB_CONTAINER }}"
            export AZURE_BLOB_CONNECTION_STRING="${{ secrets.AZURE_BLOB_CONNECTION_STRING }}"

            export AZURE_BLOB_URL="${{ secrets.AZURE_BLOB_URL }}"
            export POLICY_INDEX_NAME="${{ secrets.POLICY_INDEX_NAME }}"

            export OPEN_AI_APIKEY="${{ secrets.OPEN_AI_APIKEY }}"
            export CLOUD_DATABASE_URL="${{ secrets.CLOUD_DATABASE_URL }}"

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker compose  -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d