name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set tag
        id: tag
        run: |
          echo "tag=$(git rev-parse "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ghcr.io/teamjude/jude:${{ steps.tag.outputs.tag }} --label service="peasy" -t ghcr.io/teamjude/jude:latest .

      - name: Push image
        run: |
          docker push ghcr.io/teamjude/jude:${{ steps.tag.outputs.tag }}